import { connect } from 'react-redux'

import ReactApp from '../Metamaps/GlobalUI/ReactApp'

function mapStateToProps(state) {
  const {
    mapId,
    mobile,
    map,
    currentUser,
    allForFiltering,
    visibleForFiltering,
    filterData,
    mapIsStarred,
    openTopic,
    hasLearnedTopicCreation,
    contextMenu,
    isNewMap,
    relevantPeopleForMap,
    openSynapse,
    synapseCardPosition,
    synapseCardSynapses,
    metacodeSets,
    participants,
    isParticipating,
    conversationLive,
    unreadMessages
  } = state

  return {
    mapId,
    mobile,
    map,
    currentUser,
    allForFiltering,
    visibleForFiltering,
    filterData,
    mapIsStarred,
    openTopic,
    hasLearnedTopicCreation,
    contextMenu,
    isNewMap,
    relevantPeopleForMap,
    openSynapse,
    synapseCardPosition,
    synapseCardSynapses,
    metacodeSets,
    participants,
    isParticipating,
    conversationLive,
    unreadMessages
  }
}

function mapDispatchToProps(dispatch)  {
  const {
    launchNewMap,
    endActiveMap,
    toggleInfoBox,
    toggleMetacode,
    toggleMapper,
    toggleSynapse,
    filterAllMetacodes,
    filterAllMappers,
    filterAllSynapses,
    openImportLightbox,
    forkMap,
    openHelpLightbox,
    onMapStar,
    onMapUnstar,
    onZoomExtents,
    onZoomIn,
    onZoomOut,
    initNewTopic,
    initNewSynapse,
    openMetacodeSwitcher,
    selectMapPermission,
    deleteActiveMap,
    updateThumbnail,
    onInfoBoxMount,
    removeCollaborator,
    onSynapseCardMount,
    onSynapseDirectionChange,
    onSynapsePermissionSelect,
    onSynapseSelect,
    updateTopic,
    onTopicFollow,
    redrawCanvas,
    onOpen,
    onClose,
    leaveCall,
    joinCall,
    inviteACall,
    inviteToJoin,
    videoToggleClick,
    cursorToggleClick,
    soundToggleClick
  } = ReactApp.getCallbackProps()

  return {
    launchNewMap,
    endActiveMap,  
    toggleInfoBox,
    toggleMetacode,
    toggleMapper,
    toggleSynapse,
    filterAllMetacodes,
    filterAllMappers,
    filterAllSynapses,
    openImportLightbox,
    forkMap,
    openHelpLightbox,
    onMapStar,
    onMapUnstar,
    onZoomExtents,
    onZoomIn,
    onZoomOut,
    initNewTopic,
    initNewSynapse,
    openMetacodeSwitcher,
    selectMapPermission,
    deleteActiveMap,
    updateThumbnail,
    onInfoBoxMount,
    removeCollaborator,
    onSynapseCardMount,
    onSynapseDirectionChange,
    onSynapsePermissionSelect,
    onSynapseSelect,
    updateTopic,
    onTopicFollow,
    redrawCanvas,
    onOpen,
    onClose,
    leaveCall,
    joinCall,
    inviteACall,
    inviteToJoin,
    videoToggleClick,
    cursorToggleClick,
    soundToggleClick
  }
}

export default {
  mapStateToProps,
  mapDispatchToProps
}